### ISSUE TITLE
仅支持写在 html 里面的 js？

### ISSUE THREAD

**Issue by lmk123** [fex-team/fis-amd-demo#2]
我把 [echartsasync.html](https://github.com/fex-team/fis-amd-demo/blob/master/echartsasync.html) 里最后面那段 js 另存为一个 js 文件，再通过 `src` 属性引用进来并重新编译之后，发现 `<head>` 标签里就会有一大堆异步加载的脚本——也就是说，编译没有生效，本来应该有的 `page_map_0.js` 也没有了。

F.I.S 能做到像 [r.js](https://github.com/jrburke/r.js) 那样直接从 js 文件里分析模块依赖吗？

**Comment by 2betop** [comment]
请问你 fis release 的时候有没有带 `--pack` 属性 或者 `-p`

**Comment by lmk123** [comment]
有

**Comment by 2betop** [comment]
如果，还是有零碎的文件，你需要在[这块](https://github.com/fex-team/fis-amd-demo/blob/master/fis-conf.js#L50-L65)加上一条配置。

假如你新建的文件是 /app/a.js

``` javascript
fis.config.set('pack', {

    // a 依赖的所有文件都被打包在 pkg/a.js 里面
    'pkg/a.js': './app/a.js'
}); 
```

**Comment by lmk123** [comment]
依然如此。

我再完整描述一下我的改动：

首先，我把 [echartsasync.html](https://github.com/fex-team/fis-amd-demo/blob/master/echartsasync.html) 里最后那一段 js：

``` html
<script type="text/javascript">
    /* 简单的加上 `fis async` 注释就可以了, 表示以下的 require 不是同步加载，而是异步加载，默认所有的 require 入口都是同步，所以这里要加个注释，才能走按异步方式加载。 */
    require(['app/echarts'], function (app) {
        app();
    });
</script>
```

另存为了 `my-js.js`，并放在了我自己新建的 `js` 目录下，也就是说这个文件路径为 `js/my-js.js`；

然后，我按照你上面所说的方法，在 `pack` 设置里添加了一段：

``` js
fis.config.set( 'pack' , {
'pkg/my-js.js' : 'js/my-js.js' ,

// 下面全都照旧
});
```

并使用命令：

```
fis release -p
```

编译，之后我打开 http://127.0.0.1:8080/echartsasync.html ，发现 `html` 引用的仍然是 `js/my-js.js` ，而不是 `pkg/my-js.js` ；我自己手动在输出目录将它改了过来，然后刷新浏览器，可是 `<head>` 标签内仍然有一大堆异步加载的脚本，`page_map_0.js` 也还是没有。

**Comment by 2betop** [comment]
autoload 不能分析到通过 `<script>` 引用的资源，只能分析到文件的依赖。

 修改 

``` html
<script type="text/javascript" src=""></script>
```

成

``` html
<!--@require ./js/my-js.js-->
```

结果如图：

![image](https://cloud.githubusercontent.com/assets/2698393/6057835/b5848690-ad5c-11e4-8bfd-4b205150a6d5.png)

**Comment by lmk123** [comment]
有效，thanks。
