### ISSUE TITLE
有什么办法可以保留其它 require.js 的配置吗？

### ISSUE THREAD

**Issue by lmk123** [fex-team/fis-amd-demo#3]
我发现 demo 的异步加载原理其实就是生成了 `page_map_0.js` ，这里面设置了模块到文件路径的对应关系；但是我的项目中还有其它设置，有什么办法能将已有设置和 fis 生成的 `paths` 合并吗？

**Comment by oxUnd** [comment]
如果是你自己开发的组件，就直接交给 FIS 托管呗。

**Comment by 2betop** [comment]
本来就是 merge 进去的，你自己写的难道丢失了？

**Comment by lmk123** [comment]
@2betop 是不是我需要把其它设置写进`fis.config.set('settings.postprocessor.amd', {})`里面去，那么fis就会帮我合并进`page_map`里面去？

**Comment by 2betop** [comment]
不会，你你可以自己引入你自己的配置文件，不一定要放在一起，每次都是扩充的！

**Comment by lmk123** [comment]
demo 里面似乎没有给出示例，还是说我只需要把我的设置(比如 `require-config.js`)与 require.js 打包成一个 js 文件就可以了？

**Comment by lmk123** [comment]
@xiangshouding 这正是我想做的事情，只是我今天刚接触 fis，所以很多东西都不了解。我现有的项目是基于 require.js 进行开发的，但是它不支持增量更新(虽然有一个 `urlArgs` 设置可用，但它会被加在所有模块后面)

**Comment by lmk123** [comment]
我知道了，`requirejs.config()` 是可以调用多次的，是我没理解，sorry
