### ISSUE TITLE
define is not defined

### ISSUE THREAD

**Issue by PetersonLian** [fex-team/fis-amd-demo#7]
fis-conf.js: 

```
// // 开起 autuload, 好处是，依赖自动加载。
fis.config.set('modules.postpackager', 'autoload');
fis.config.set('settings.postpackager.autoload.type', 'requirejs');
// fis.config.set('settings.postpackager.autoload.type', 'mod');

fis.config.merge({
   modules : {
    parser : {
        less : ['less']
    },
    postprocessor: {
        js : 'amd',
        html: 'amd'            
    },
    packager: ['depscombine']
 },
 settings : {
    postprocessor : {
        amd : {
            baseUrl: 'js/lib',

            paths: {
                zepto: 'zepto.js',
                app: '../app.js',
                main: '../app/main.js',
                loader: '../app/component/loader.js'
            },

            shim: {

            }
        }
    }
    },
  roadmap:{
    ext : {
        less : 'css'
    }// ,
    // path : [
    // {
    //     reg: '/.*js\/.*\.js/i',
    //     isMod: true
    // }
    // ],
     ,pack:{
        'pkg/app.js': [
            'js/app.js'
        ]
    }
    }
 });
```

index.html: 

```
<script type="text/javascript" src="js/lib/require.js"></script>
<script type="text/javascript">
  require(['main'], function() {

  });
</script>
```

然后老是报错,define和require都是undefined的。  

目的在于，也许有人一看，“hey,这是很简单的幼稚错误”就顺手给我解决了。故而，我就没放详细描述。

**Comment by oxUnd** [comment]
- 看看访问页面源码，`require.js` 被加载到什么地方了，是否是在所有 js 之前。

**Comment by PetersonLian** [comment]
@xiangshouding 是放在所有js之前(都放在body最后)。  
我的代码同fis-amd-demo的里头的源码的区别在于：我的代码的define，都是有手写前置依赖的。例如：  

```
define(['deps1', 'deps2'], function(dep1, dep2){
});  
```

这个问题，应该是我某处代码写不对。不准备继续跟进了。  

倒是,fis-amd-demo里头提到的

> /\* 简单的加上 `fis async` 注释就可以了, 表示以下的 require 不是同步加载，而是异步加载，默认所有的 require 入口都是同步，所以这里要加个注释，才能走按异步方式加载。 */  

问：fis不太熟，如何加下`fis async`注释？给个例子呗。

**Comment by 2betop** [comment]
是这样的，amd 其实是没有同步 require 的，同步 require 的目的是为了让依赖提前被 `<script>`  引入进来, 那么既然没有同步 require,  我们就弄个其他方式，就是让所有 全局 require 都认为是同步，然后让某些不希望被认为是同步的 require 让其在前一行的注释里面加上 `fis async` 字样，这样编译工具会认为这个依赖是是异步的。目标资源就不会提前通过 `<script>` 引入进来了，而是真正运行到这段的时候，由 amd loader 去加载。

不过关于是否需要将所有全局 require 认为是同步，这个其实是有个开关的，默认是开的，如果觉得这个功能不符合你的预期，是可以关掉的。详情见这里的[配置说明](https://github.com/fex-team/fis-postprocessor-amd)
